author: gojudge2008@gmail.com
description: >
        Ojsite - web app for Goj

filesets:
    includes:
        - conf
        - fis
        - custom
        - scripts
        - views
        - README.md
        - LICENSE
    excludes:
        - \.git
    depth: 3
settings:
        targetdir: ""
        build: |
            go install